apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notificaciones
  name: notificaciones
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: notificaciones
  type: ClusterIP
