apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notificaciones
  name: notificaciones
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
      - image: docker.io/cafaray/notificaciones:v2
        name: notificaciones
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
          requests:
            cpu: '1'
            memory: 128Mi


---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notificaciones
  name: notificaciones
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: notificaciones
  type: ClusterIP

